name: Deploy to AWS ECS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin <your-ecr-repo-url>

      - name: Build and Push Docker Image
        run: |
          docker build -t ecommerce-app .
          docker tag ecommerce-app <your-ecr-repo-url>:latest
          docker push <your-ecr-repo-url>:latest

      - name: Deploy with Terraform
        run: |
          terraform init
          terraform apply -auto-approve
